// Code generated by ogen, DO NOT EDIT.

package techempower

import (
	"github.com/shiroma-lukas/ogen-multispec/middleware"
)

// Middleware is middleware type.
type Middleware = middleware.Middleware
