// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/shiroma-lukas/ogen-multispec/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateItems implements createItems operation.
//
// Create deeply nested items.
//
// POST /test/items
func (UnimplementedHandler) CreateItems(ctx context.Context, req *CreateItemsReq) (r *CreateItemsOK, _ error) {
	return r, ht.ErrNotImplemented
}
