// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/shiroma-lukas/ogen-multispec/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetData implements getData operation.
//
// GET /data
func (UnimplementedHandler) GetData(ctx context.Context) (r Data, _ error) {
	return r, ht.ErrNotImplemented
}
