// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/shiroma-lukas/ogen-multispec/validate"
)

func decodeAliveResponse(resp *http.Response) (res *AliveOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AliveOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
