// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/shiroma-lukas/ogen-multispec/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetConfig implements getConfig operation.
//
// GET /config
func (UnimplementedHandler) GetConfig(ctx context.Context) (r Config, _ error) {
	return r, ht.ErrNotImplemented
}
